### ISSUE TITLE
Add a buildbot test to ensure z.cash/depends-sources is up to date.

### ISSUE THREAD

**Issue by nathan-at-least** [Electric-Coin-Company/zcash#631]

**Comment by defuse** [comment]
Here's a proposed architecture: There's a list of commit hashes, and for each one, we check it out, build `./depends`, and check that every file in `./depends/sources/` is present on the server.

Why a list of commit hashes, and not just the latest one? Because we want old code to keep working.

Open question: Should it download and verify the contents of the file is the same, or should it just check that it exists and has the same size via an HTTP `HEAD`?

**Comment by defuse** [comment]
I wrote the test. It's in PR #694. Once that's merged, add it to buildbot.

**Comment by defuse** [comment]
I added a nightly test and it's passing.
