### ISSUE TITLE
noob: is getnewaddress public or secret?

### ISSUE THREAD

**Issue by petjal** [Electric-Coin-Company/zcash#661]
>https://github.com/Electric-Coin-Company/zcash/wiki/Public-Alpha-Guide

Says to 

>Generate a new "transparent" (Bitcoin-style) address like so:
>./src/zcash-cli getnewaddress
>mojH91FkurYJzQyYEVFRBYxTNbsUpPkJEQ
>Then come visit us on irc.oftc.net in channel #zcash and we'll gladly give you some!

Question: is that "mojH91FkurYJzQyYEVFRBYxTNbsUpPkJEQ" a freely publishable public zcash address, to which anybody and everybody can send zcash?   Will I be pasting that at irc channel #zcash?  

I presume irc channel #zcash at https://webchat.freenode.net/ is OK?

Will we ever publish the zcaddress generated with zcrawkeygen to request zcash or should that be kept secret?  

Maybe I need a link to another doc?

Thanks!

**Comment by ebfull** [comment]
`getnewaddress` returns a Bitcoin-style "transparent address". This is an RPC call available in upstream Bitcoin and the address and transaction semantics are identical. These addresses are not part of our confidentiality scheme. We augment Bitcoin with our own scheme which uses different kinds of addresses. The two schemes co-exist and you can transfer between them at will.

Our "confidential addresses" can be generated with `zcrawkeygen`. Transactions involving these addresses do not indicate to the public where the value was sent, not even to people who have your address, so you can publish these publicly. Re-use of these addresses is completely normal as they roughly equate to *identities*.

The reason the guide asks you to generate a "transparent address" (Bitcoin-style) is so that you can then send them to your own "confidential address" using the pour operation.

As an alternative the guide *could* just ask you to generate a confidential address and we could send you some zcash to play with, but then *we* would have to perform the pour, which takes a couple minutes (currently) due to inefficiencies in the scheme that we're ironing out. It's easier for us if we make you do the pour. :)
