### ISSUE TITLE
Why is absurd ("insane") fee rejection disabled?

### ISSUE THREAD

**Issue by nathan-at-least** [Electric-Coin-Company/zcash#84]
In [./src/main.cpp L748](https://github.com/Electric-Coin-Company/zerocashd/blob/get_being_strange/src/main.cpp#L748) it appears we disable absurd fee rejection, where it is not disabled upstream, with ``fRejectInsaneFee = fFalse``.

What is the rationale behind this?

**Note**: In upstream master, this variable has been renamed to ``fRejectAbsurdFee``.

**Comment by ebfull** [comment]
This is not a problem anymore for us, our tests just don't run into this issue.

It's important that this remains a consensus rule for now. Otherwise a large fee would change the incentive structure for the blockchain: suddenly, miners would have enormous incentive to focus on orphaning each other and attempting to outpace each other.
